[package]
name = "nt-token"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.57", features = [
     "Win32_Foundation",
     "Win32_Security",
     "Win32_Security_Authorization",
     "Win32_System_Threading",
     "Win32_System_Memory",
] }
